name: loopdraw
channels:
  - defaults

dependencies:
  - python=3.8
  - pytorch::pytorch
  - cudatoolkit=11.3
  - pytorch::torchvision
  - fvcore::fvcore
  - iopath::iopath
  - conda-forge::polyscope
  - conda-forge::pyvista
  - conda-forge::scipy
  - matplotlib
  - pip
  - pip:
    - pymeshlab
